services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9002:9000" # Map external port 9001 to internal port 9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: